server:  
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}



spring:
  jpa:
    show-sql: true
    database: sql-server
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:169.56.174.139}:${DB_PORT:31953}/${DB_NAME:test}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:passw0rd}
    sql-script-encoding: utf-8
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
  session:
    store-type: jdbc


#hibernate.globally_quoted_identifiers=true
